from uuid import UUID

from fastapi.testclient import TestClient

from app.api import routes_trip
from app.main import create_app
from app.schemas.domain import DayPlan, Meal
from app.schemas.trip import TripPlan


def minimal_trip_request() -> dict:
    return {
        "user_id": "user-001",
        "cities": ["Beijing"],
        "start_date": "2026-06-10",
        "end_date": "2026-06-12",
        "preferences": {
            "transport_preference": 0,
            "accommodation_preference": [0],
            "attraction_preference": [0, 1],
        },
        "budget": 3000,
        "extra_requirements": "Keep the pace relaxed",
    }


def test_plan_endpoint_generates_session_id_for_first_request() -> None:
    client = TestClient(create_app())

    response = client.post("/api/trip/plan", json=minimal_trip_request())

    assert response.status_code == 200
    trip_plan = TripPlan.model_validate(response.json())
    UUID(trip_plan.session_id)
    assert trip_plan.cities == ["Beijing"]
    assert len(trip_plan.days) == 3
    assert [meal.type for meal in trip_plan.days[0].meals] == ["breakfast", "lunch", "dinner"]


def test_plan_endpoint_reuses_existing_session_id() -> None:
    client = TestClient(create_app())
    payload = minimal_trip_request()
    payload["session_id"] = "existing-session-001"

    response = client.post("/api/trip/plan", json=payload)

    assert response.status_code == 200
    trip_plan = TripPlan.model_validate(response.json())
    assert trip_plan.session_id == "existing-session-001"


def test_plan_endpoint_returns_trip_plan_from_graph(monkeypatch) -> None:
    class FakeGraph:
        async def ainvoke(self, state: dict, config: dict) -> dict:
            request = state["request"]
            session_id = config["configurable"]["thread_id"]
            return {
                "trip_plan": TripPlan(
                    session_id=session_id,
                    cities=request.cities,
                    start_date=request.start_date,
                    end_date=request.start_date,
                    days=[
                        DayPlan(
                            date=request.start_date,
                            day_index=0,
                            city=request.cities[0],
                            description="Graph-owned response",
                            transportation="public_transport",
                            accommodation="budget_hotel",
                            meals=[
                                Meal(type="breakfast", name="Graph breakfast"),
                                Meal(type="lunch", name="Graph lunch"),
                                Meal(type="dinner", name="Graph dinner"),
                            ],
                            total_price=1,
                        )
                    ],
                    weather_info=[],
                    overall_suggestions="Generated by fake graph",
                )
            }

    monkeypatch.setattr(routes_trip, "build_travel_planner_graph", lambda: FakeGraph(), raising=False)
    client = TestClient(create_app())
    payload = minimal_trip_request()
    payload["start_date"] = "2026-06-10"
    payload["end_date"] = "2026-06-10"

    response = client.post("/api/trip/plan", json=payload)

    assert response.status_code == 200
    trip_plan = TripPlan.model_validate(response.json())
    assert trip_plan.overall_suggestions == "Generated by fake graph"
    assert trip_plan.days[0].description == "Graph-owned response"
