import asyncio
import json
from datetime import date

from app.agents.nodes import make_planner_node, planner_node, validate_trip_plan
from app.schemas.domain import Attraction, Hotel, Location, MapPoint, WeatherInfo
from app.schemas.graph import NormalizedTripRequest, TravelPlanState
from app.schemas.trip import TripPlan


def normalized_request() -> NormalizedTripRequest:
    return NormalizedTripRequest(
        user_id="user-001",
        cities=["Beijing"],
        start_date="2026-06-10",
        end_date="2026-06-11",
        days_count=2,
        transport_preference="public_transport",
        accommodation_preferences=["budget_hotel"],
        attraction_preferences=["history_culture"],
        budget=2000,
        extra_requirements="Keep the pace relaxed",
        session_id="session-planner-001",
    )


def planner_state() -> TravelPlanState:
    return {
        "normalized_request": normalized_request(),
        "planner_context": "[Planner Context]\nUse candidate data.",
        "attractions": [
            Attraction(
                name=f"Attraction {index}",
                city="Beijing",
                address=f"Attraction Road {index}",
                poi_id=f"A-{index}",
                ticket_price=20,
                location=Location(longitude=116.3 + index * 0.001, latitude=39.9),
            )
            for index in range(4)
        ],
        "hotels": [
            Hotel(
                name="Central Hotel",
                city="Beijing",
                address="Hotel Road 1",
                poi_id="H-1",
                estimated_cost=450,
                distance_to_main_area_km=2.5,
                estimated_travel_time_minutes=18,
                transit_method="transit",
                location=Location(longitude=116.4, latitude=39.91),
            )
        ],
        "weather_info": [
            WeatherInfo(
                city="Beijing",
                date=date(2026, 6, 10),
                day_weather="sunny",
                night_weather="cloudy",
                day_temp=28,
                night_temp=18,
            )
        ],
    }


def test_planner_node_fallback_uses_candidates_to_build_renderable_trip_plan() -> None:
    async def run_node() -> TravelPlanState:
        return await planner_node(planner_state())

    result = asyncio.run(run_node())
    trip_plan = TripPlan.model_validate(result["trip_plan"])

    assert trip_plan.overall_suggestions != "Mock trip plan generated by TravelPlannerGraph."
    assert trip_plan.weather_info == planner_state()["weather_info"]
    assert len(trip_plan.days) == 2
    assert [len(day.meals) for day in trip_plan.days] == [3, 3]
    assert [meal.type for meal in trip_plan.days[0].meals] == ["breakfast", "lunch", "dinner"]
    assert [attraction.name for attraction in trip_plan.days[0].attractions] == ["Attraction 0", "Attraction 1"]
    assert [attraction.name for attraction in trip_plan.days[1].attractions] == ["Attraction 2", "Attraction 3"]
    assert trip_plan.days[0].hotel is not None
    assert trip_plan.days[0].hotel.name == "Central Hotel"
    assert trip_plan.days[0].route_distance_km == 2.5
    assert trip_plan.days[0].route_duration_minutes == 18
    assert trip_plan.days[0].transit_method == "transit"
    assert [point.point_type for point in trip_plan.days[0].map_points] == ["attraction", "attraction", "hotel"]
    assert trip_plan.days[0].total_price == 550


def test_planner_node_fallback_caps_relaxed_single_day_attractions_and_estimates_hotel_cost() -> None:
    request = normalized_request().model_copy(
        update={
            "start_date": date(2026, 12, 25),
            "end_date": date(2026, 12, 25),
            "days_count": 1,
            "accommodation_preferences": ["mid_level_hotel"],
            "extra_requirements": "中文输出；一天轻松行程；不要太赶。",
        }
    )
    state = planner_state()
    state["normalized_request"] = request
    state["attractions"] = [
        Attraction(
            name=f"Hangzhou Attraction {index}",
            city="Hangzhou",
            address=f"Attraction Road {index}",
            poi_id=f"HZ-A-{index}",
            location=Location(longitude=120.1 + index * 0.001, latitude=30.2),
        )
        for index in range(12)
    ]
    state["hotels"] = [
        Hotel(
            name="Hangzhou Mid Hotel",
            city="Hangzhou",
            address="Hotel Road 1",
            poi_id="HZ-H-1",
            type="住宿服务;宾馆酒店;宾馆酒店",
            estimated_cost=0,
            location=Location(longitude=120.16, latitude=30.25),
        )
    ]

    result = asyncio.run(planner_node(state))
    trip_plan = TripPlan.model_validate(result["trip_plan"])

    assert len(trip_plan.days) == 1
    assert len(trip_plan.days[0].attractions) == 3
    assert trip_plan.days[0].hotel is not None
    assert trip_plan.days[0].hotel.estimated_cost == 600
    assert trip_plan.days[0].total_price == 660


def test_validate_trip_plan_rejects_too_many_attractions_for_relaxed_day() -> None:
    request = normalized_request().model_copy(
        update={
            "start_date": date(2026, 12, 25),
            "end_date": date(2026, 12, 25),
            "days_count": 1,
            "extra_requirements": "一天轻松行程，不要太赶。",
        }
    )
    attractions = [
        Attraction(
            name=f"Attraction {index}",
            city="Hangzhou",
            location=Location(longitude=120.1 + index * 0.001, latitude=30.2),
        )
        for index in range(6)
    ]
    trip_plan = TripPlan(
        session_id="session-planner-001",
        cities=["Beijing"],
        start_date=date(2026, 12, 25),
        end_date=date(2026, 12, 25),
        days=[
            {
                "date": date(2026, 12, 25),
                "day_index": 0,
                "city": "Beijing",
                "description": "Too dense.",
                "transportation": "public_transport",
                "accommodation": "budget_hotel",
                "attractions": attractions,
                "map_points": [
                    MapPoint(
                        name=attraction.name,
                        city=attraction.city,
                        location=attraction.location,
                        day_index=0,
                        order_index=index,
                    )
                    for index, attraction in enumerate(attractions)
                    if attraction.location is not None
                ],
                "total_price": 100,
            }
        ],
        weather_info=[],
        overall_suggestions="Too dense.",
    )
    state = {
        "normalized_request": request,
        "trip_plan": trip_plan,
        "tool_observations": [],
        "memory_candidates": [],
    }

    result = asyncio.run(validate_trip_plan(state))

    assert any("must not include more than 3 attractions" in error for error in result["validation_errors"])


def test_planner_node_uses_llm_structured_trip_plan_when_service_is_available() -> None:
    class FakeLLM:
        def __init__(self) -> None:
            self.messages: list[list[dict]] = []

        async def complete(self, messages: list[dict], **_: object) -> dict:
            self.messages.append(messages)
            payload = {
                "session_id": "session-planner-001",
                "cities": ["Beijing"],
                "start_date": "2026-06-10",
                "end_date": "2026-06-11",
                "days": [
                    {
                        "date": "2026-06-10",
                        "day_index": 0,
                        "city": "Beijing",
                        "description": "LLM planned day.",
                        "transportation": "public_transport",
                        "accommodation": "budget_hotel",
                        "meals": [
                            {"type": "breakfast", "name": "Breakfast", "city": "Beijing"},
                            {"type": "lunch", "name": "Lunch", "city": "Beijing"},
                            {"type": "dinner", "name": "Dinner", "city": "Beijing"},
                        ],
                        "total_price": 120,
                    },
                    {
                        "date": "2026-06-11",
                        "day_index": 1,
                        "city": "Beijing",
                        "description": "LLM planned second day.",
                        "transportation": "public_transport",
                        "accommodation": "budget_hotel",
                        "meals": [
                            {"type": "breakfast", "name": "Breakfast", "city": "Beijing"},
                            {"type": "lunch", "name": "Lunch", "city": "Beijing"},
                            {"type": "dinner", "name": "Dinner", "city": "Beijing"},
                        ],
                        "total_price": 130,
                    },
                ],
                "weather_info": [
                    {
                        "city": "Beijing",
                        "date": "2026-06-10",
                        "day_weather": "sunny",
                        "night_weather": "cloudy",
                        "day_temp": 28,
                        "night_temp": 18,
                    }
                ],
                "overall_suggestions": "LLM generated plan.",
            }
            return {"choices": [{"message": {"content": json.dumps(payload)}}]}

    async def run_node() -> tuple[TravelPlanState, FakeLLM]:
        llm = FakeLLM()
        node = make_planner_node(llm_service=llm)
        return await node(planner_state()), llm

    result, llm = asyncio.run(run_node())
    trip_plan = TripPlan.model_validate(result["trip_plan"])
    prompt_text = "\n".join(message["content"] for message in llm.messages[0])

    assert trip_plan.overall_suggestions == "LLM generated plan."
    assert trip_plan.session_id == "session-planner-001"
    assert "Use candidate data" in prompt_text
    assert "Attraction 0" in prompt_text
    assert "Central Hotel" in prompt_text
    assert "TripPlan" in prompt_text
