import asyncio

from app.agents.trip_planner_agent import build_travel_planner_graph
from app.schemas.graph import TravelPlanState
from app.schemas.trip import TripPlan, TripPlanRequest, TripPreferencesInput


def make_request() -> TripPlanRequest:
    return TripPlanRequest(
        user_id="user-001",
        session_id="session-graph-001",
        cities=["Beijing"],
        start_date="2026-06-10",
        end_date="2026-06-12",
        preferences=TripPreferencesInput(
            transport_preference=0,
            accommodation_preference=[0],
            attraction_preference=[0, 1],
        ),
        budget=3000,
        extra_requirements="Keep the pace relaxed",
    )


def test_minimal_travel_planner_graph_outputs_valid_trip_plan() -> None:
    async def run_graph() -> TravelPlanState:
        graph = build_travel_planner_graph()
        request = make_request()
        return await graph.ainvoke(
            {"request": request},
            config={"configurable": {"thread_id": request.session_id}},
        )

    result = asyncio.run(run_graph())

    trip_plan = TripPlan.model_validate(result["trip_plan"])
    assert result["normalized_request"].session_id == "session-graph-001"
    assert trip_plan.session_id == "session-graph-001"
    assert len(trip_plan.days) == 3
    assert trip_plan.overall_suggestions == "Mock trip plan generated by TravelPlannerGraph."
