import asyncio
from datetime import date

from app.agents.trip_planner_agent import build_travel_planner_graph
from app.schemas.domain import WeatherInfo
from app.schemas.graph import TravelPlanState
from app.schemas.trip import TripPlan, TripPlanRequest, TripPreferencesInput


def make_request() -> TripPlanRequest:
    return TripPlanRequest(
        user_id="user-001",
        session_id="session-graph-001",
        cities=["Beijing"],
        start_date="2026-06-10",
        end_date="2026-06-12",
        preferences=TripPreferencesInput(
            transport_preference=0,
            accommodation_preference=[0],
            attraction_preference=[0, 1],
        ),
        budget=3000,
        extra_requirements="Keep the pace relaxed",
    )


def test_minimal_travel_planner_graph_outputs_valid_trip_plan() -> None:
    async def run_graph() -> TravelPlanState:
        graph = build_travel_planner_graph()
        request = make_request()
        return await graph.ainvoke(
            {"request": request},
            config={"configurable": {"thread_id": request.session_id}},
        )

    result = asyncio.run(run_graph())

    trip_plan = TripPlan.model_validate(result["trip_plan"])
    assert result["normalized_request"].session_id == "session-graph-001"
    assert trip_plan.session_id == "session-graph-001"
    assert len(trip_plan.days) == 3
    assert trip_plan.overall_suggestions == "Mock trip plan generated by TravelPlannerGraph."


def test_travel_planner_graph_queries_weather_before_planning() -> None:
    class WeatherClient:
        def __init__(self) -> None:
            self.calls: list[str] = []

        async def get_weather(self, city: str) -> list[WeatherInfo]:
            self.calls.append(city)
            return [
                WeatherInfo(
                    city=city,
                    date=date(2026, 6, 10),
                    day_weather="sunny",
                    night_weather="cloudy",
                    day_temp=28,
                    night_temp=18,
                    wind_direction="east",
                    wind_power="1-3",
                )
            ]

    async def run_graph() -> tuple[TravelPlanState, WeatherClient]:
        client = WeatherClient()
        graph = build_travel_planner_graph(amap_client=client)
        request = make_request()
        result = await graph.ainvoke(
            {"request": request},
            config={"configurable": {"thread_id": request.session_id}},
        )
        return result, client

    result, client = asyncio.run(run_graph())

    trip_plan = TripPlan.model_validate(result["trip_plan"])
    assert client.calls == ["Beijing"]
    assert len(result["weather_info"]) == 1
    assert trip_plan.weather_info == result["weather_info"]
    assert "Amap weather query for Beijing returned 1 records." in result["tool_observations"]


def test_travel_planner_graph_keeps_planning_when_weather_fails() -> None:
    class FailingWeatherClient:
        async def get_weather(self, city: str) -> list[WeatherInfo]:
            raise RuntimeError("weather unavailable")

    async def run_graph() -> TravelPlanState:
        graph = build_travel_planner_graph(amap_client=FailingWeatherClient())
        request = make_request()
        return await graph.ainvoke(
            {"request": request},
            config={"configurable": {"thread_id": request.session_id}},
        )

    result = asyncio.run(run_graph())

    trip_plan = TripPlan.model_validate(result["trip_plan"])
    assert trip_plan.weather_info == []
    assert result["weather_info"] == []
    assert "Amap weather query for Beijing failed: RuntimeError." in result["tool_observations"]
